name = "anbsn-engine"
main = "worker.js"
compatibility_date = "2026-07-27"

[vars]
# Public variables go here, secrets stay in the dashboard or GitHub secrets
PROTOCOL = "05Fa"

[[workflows]]
name = "anbsn-global-workflow"
binding = "MY_WORKFLOW"
class_name = "MyWorkflow"
